Dashboard UI
rudolfstorsters/CarChargeUnlock pull request #8
Opened 2022-02-03 13:51 UTC by rudolfstorsters

Add Card For Dashboard

2022-02-04 13:49 UTC, armadilio3 commented on client/components/common/dashboardCard.js
> +        this.state = {
Move to a simple variable declaration instead of setting initial state in constructor

2022-02-04 13:54 UTC, armadilio3 requested changes
Left some notes. Please deploy to the test server so I can take a look.

2022-02-04 13:54 UTC, armadilio3 commented on client/components/common/rangeSlider.js
> +                <p>Car charger can be unlocked at
Move text to next line

2022-02-04 13:54 UTC, armadilio3 commented on client/components/pages/DashboardPage/AddCarPage.js
> +        const {
Do this in a single line

2022-02-04 13:54 UTC, armadilio3 commented on client/components/pages/DashboardPage/AuthMethod.js
> +export const TESLAACCOUNT = 'tesla';
```suggestion
export const TESLA_ACCOUNT = 'tesla';
```

2022-02-04 13:54 UTC, armadilio3 commented on client/components/pages/DashboardPage/AuthMethod.js
> +export const APIKEY = 'api';
```suggestion
export const API_KEY = 'api';
```

2022-02-04 13:54 UTC, armadilio3 commented on client/components/pages/WelcomePage/WelcomePage.js
> +
Remove whitespace

2022-02-04 13:54 UTC, armadilio3 commented on client/styles/dashboard.scss
> +  }
Add newline

2022-02-04 13:54 UTC, armadilio3 commented on client/styles/navigation.scss
> +   justify-items: space-between;
Align

2022-02-14 16:51 UTC, armands-malejevs approved these changes
Great work!

2022-02-15 14:32 UTC, merged